services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.2
    container_name: elastic
    volumes:
      - elastic:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
    mem_limit: 1073741824
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: curl --fail --silent localhost:9200/_cluster/health?filter_path=status | grep -q "green\|yellow"
      interval: 10s
      timeout: 10s
      retries: 120
  # kibana:
  #   image: docker.elastic.co/kibana/kibana:8.13.2
  #   container_name: kibana
  #   depends_on:
  #     elastic:
  #       condition: service_healthy
  #   volumes:
  #     - kibana:/usr/share/kibana/data
  #   ports:
  #     - 5601:5601
  #   environment:
  #     - SERVERNAME=kibana
  #     - ELASTICSEARCH_HOSTS=http://elastic:9200
  #     - TELEMETRY_ENABLED=false
  #   mem_limit: 1073741824
  #   healthcheck:
  #     test:
  #       [
  #         "CMD-SHELL",
  #         "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'",
  #       ]
  #     interval: 10s
  #     timeout: 10s
  #     retries: 120
  ingest:
    build: ingest
    container_name: ingest
    depends_on:
      elastic:
        condition: service_healthy
    environment:
      - LOG_LEVEL=DEBUG
      - ELASTIC_SERVER_URL=http://elastic:9200
      - DUMP_DATE=20240415
    volumes:
      - ingest:/ingest/success
volumes:
  elastic:
  # kibana:
  ingest:
