services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.2
    container_name: elastic
    volumes:
      - elastic:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
    mem_limit: 1073741824
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: curl --fail --silent localhost:9200/_cluster/health?filter_path=status | grep -q "green\|yellow"
      interval: 10s
      timeout: 10s
      retries: 120
  ingest:
    build: ingest
    container_name: ingest
    depends_on:
      elastic:
        condition: service_healthy
    environment:
      - LOG_LEVEL=DEBUG
      - ELASTIC_SERVER_URL=http://elastic:9200
      - DUMP_DATE=20240415
    volumes:
      - ingest:/ingest/success
  api:
    build: api
    container_name: api
    depends_on:
      elastic:
        condition: service_healthy
    environment:
      - ELASTIC_SERVER_URL=http://elastic:9200
    ports:
      - "3000:80"
    volumes:
      - api:/api/data
  frontend:
    build: frontend
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      elastic:
        condition: service_healthy
  reverse-proxy:
    image: nginx:1.25.5-alpine
    container_name: reverse-proxy
    ports:
      - "8080:80"
    restart: always
    depends_on:
      elastic:
        condition: service_healthy
    volumes:
      - ./reverse-proxy/default.conf:/etc/nginx/conf.d/default.conf
volumes:
  elastic:
  ingest:
  api:
